version: '3'
services:
  tweeter_backend:
    container_name: tweeter_backend
    build: ./Tweeter_backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: python ./manage.py runserver 0:8000
  tweeter_frontend:
    container_name: tweeter_frontend
    build: ./Tweeter_frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - tweeter_backend
    command: npm start
